### PR TITLE
Ruvetia #8: Basel

### PR DESCRIPTION
**Pull request by danielpuglisi**
It's been a long time since the last Ruvetia event. 

:tada: :tada: :tada: Time for another one! :tada: :tada: :tada:

The event will take place in Basel (location to be announced) but I still need some feedback on the date. Do you guys have time on May the 8th?

### CODE REVIEW

**Comment by senny** [comment]
:tada: :tada: :sparkles: :tada: :tada: 

@danielpuglisi the build is failing :broken_heart: :sob:

**Comment by danielpuglisi** [comment]
Fixed :)

**Comment by senny** [comment]
@danielpuglisi deployed. You can now announce it on twitter.

**Comment by danielpuglisi** [comment]
Done. 


Retweet please: https://twitter.com/ruvetia/status/592617242690326529

**Comment by senny** [comment]
@danielpuglisi can you write a post to the Mailing-List as well? https://groups.google.com/forum/#!forum/ruvetia

We should probably pitch it on twitter again. Not many seem signed up...

**Comment by danielpuglisi** [comment]
Done

**Comment by senny** [comment]
@danielpuglisi :yellow_heart:

**Pull request merged**
